test:
	python -m scripts.test_shape

trainrm:
	rm -rf fullout

devrm:
	rm -rf devout

convnet:
	python -m scripts.train_convnet

cvconvnet:
	python -m scripts.cv_convnet

cvrm:
	rm -rf cvout

use_convnet:
	rm -rf use_out
	python -m scripts.use_convnet

from_api:
	rm -rf use_out
	python -m scripts.example_from_api
